blank_issues_enabled: false
contact_links:
  - name: General Questions & Discussion
    url: https://github.com/discussions
    about: Use Discussions for open-ended questions not suited for an issue
